# Generated by Django 5.2.18 on 2026-10-10 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seconds_read', models.PositiveIntegerField(default=0, help_text='Active reading time (tab visible, recent input).')),
                ('actions', models.PositiveIntegerField(default=0, help_text='Chapters completed, quizzes, flashcards, notes.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_reading_day')],
            },
        ),
    ]
