# Generated by Django 5.2.18 on 2026-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=120)),
                ('category_slug', models.SlugField(blank=True, max_length=140)),
                ('body_html', models.TextField(help_text='Rendered and sanitised at import time.')),
                ('excerpt', models.TextField(blank=True)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=1)),
                ('related_slugs', models.JSONField(blank=True, default=list)),
                ('wordpress_url', models.URLField(blank=True, help_text='Original post on WordPress, used as the canonical URL.', max_length=500)),
                ('source_path', models.CharField(help_text='File in the vault this post came from.', max_length=500)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide a post without deleting it.')),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
