# Generated by Django 5.2.18 on 2026-10-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='Path inside the vault.', max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='blog.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'path'), name='uniq_post_asset')],
            },
        ),
    ]
