# Generated by Django 5.2.18 on 2026-10-10 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, help_text='Shown in the lobby.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'live quizzes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('choices', models.TextField(help_text='2–4 choices, one per line. Start the correct one(s) with <code>*</code>.')),
                ('time_limit', models.PositiveSmallIntegerField(default=20, help_text='Seconds to answer (5–120).')),
                ('points', models.PositiveSmallIntegerField(default=1000, help_text='Points for an instant correct answer; answering at the last second gives half.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='arena.livequiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(db_index=True, max_length=6)),
                ('status', models.CharField(choices=[('lobby', 'Waiting for players'), ('question', 'Question open'), ('reveal', 'Showing the answer'), ('leaderboard', 'Leaderboard'), ('finished', 'Finished')], default='lobby', max_length=12)),
                ('current_index', models.IntegerField(default=-1, help_text="Index into the quiz's questions; -1 before the first.")),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='arena.livequiz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('token_hash', models.CharField(help_text="SHA-256 of the player's secret token.", max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='arena.livegame')),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveSmallIntegerField()),
                ('correct', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='arena.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_answers', to='arena.livequestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='livegame',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'finished'), _negated=True), fields=('pin',), name='uniq_active_pin'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('game', 'nickname'), name='uniq_game_nickname'),
        ),
        migrations.AddConstraint(
            model_name='playeranswer',
            constraint=models.UniqueConstraint(fields=('player', 'question'), name='uniq_player_question'),
        ),
    ]
