# Generated by Django 5.2.18 on 2026-10-10 04:03

import django.db.models.deletion
import live.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_is_common_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. “Session 12 · Kubernetes Services”.', max_length=200)),
                ('starts_at', models.DateTimeField(help_text='In India time (IST).')),
                ('ends_at', models.DateTimeField()),
                ('meet_url', models.URLField(max_length=300, validators=[live.models.validate_meeting_url], verbose_name='Google Meet link')),
                ('description', models.CharField(blank=True, help_text='Optional one-line agenda.', max_length=300)),
                ('is_cancelled', models.BooleanField(default=False, help_text='Keeps the session on the list, marked as cancelled.', verbose_name='cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
            ],
            options={
                'ordering': ['starts_at', 'course__title'],
                'indexes': [models.Index(fields=['starts_at'], name='live_livese_starts__b492f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'starts_at'), name='uniq_course_session_start')],
            },
        ),
    ]
