# Generated by Django 5.2.18 on 2026-10-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_dir', models.CharField(blank=True, help_text='Folder with the markdown files, relative to the course content root. Defaults to the slug.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('build_status', models.CharField(choices=[('never', 'Never built'), ('building', 'Building'), ('ok', 'OK'), ('failed', 'Failed')], default='never', max_length=10)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
                ('build_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
                'constraints': [models.UniqueConstraint(fields=('course', 'email'), name='uniq_course_email')],
            },
        ),
    ]
