# Generated by Django 5.2.18 on 2026-10-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_common',
            field=models.BooleanField(default=False, help_text='Open to every signed-in student without enrolling them. Leave unticked for courses only enrolled students can see.', verbose_name='Common course'),
        ),
    ]
