# Generated by Django 5.2.18 on 2026-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_page_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_common',
            field=models.BooleanField(default=False, help_text='Public: anyone can read it without signing in or enrolling. Progress tracking and quizzes are only for students you enrol below. Leave unticked for enrolled-only courses.', verbose_name='Common course'),
        ),
    ]
