# Generated by Django 5.2.18 on 2026-10-07 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter', models.CharField(blank=True, help_text='Docs page this quiz belongs to: the markdown file name without .md, e.g. <code>lesson-1</code> or <code>week-2/intro</code>. A “Take the quiz” card is shown on that page. Leave blank for a course-level quiz.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Shown before the student starts.')),
                ('is_published', models.BooleanField(default=False, help_text='Students only see published quizzes.')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='0 means unlimited attempts.')),
                ('pass_percentage', models.PositiveSmallIntegerField(default=60)),
                ('show_answers', models.BooleanField(default=True, help_text='After submitting, show correct answers and explanations.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are listed first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Markdown is supported, including `code` and ``` blocks.')),
                ('choices', models.TextField(help_text='One choice per line. Start the correct choice(s) with <code>*</code>. With more than one correct choice, students pick all that apply.')),
                ('explanation', models.TextField(blank=True, help_text='Shown after submitting (optional).')),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['quiz', 'user'], name='quizzes_att_quiz_id_2b9c61_idx')],
            },
        ),
    ]
