# Generated by Django 5.2.18 on 2026-10-08 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_is_common_help'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=models.CharField(blank=True, help_text='Docs page this belongs to: the markdown file name without .md, e.g. <code>lesson-1</code> or <code>sessions/04-llm-terminology</code>. A card linking to it is shown on that page. Leave blank for a course-level item.', max_length=200),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter', models.CharField(blank=True, help_text='Docs page this belongs to: the markdown file name without .md, e.g. <code>lesson-1</code> or <code>sessions/04-llm-terminology</code>. A card linking to it is shown on that page. Leave blank for a course-level item.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Shown before the student starts.')),
                ('is_published', models.BooleanField(default=False, help_text='Students only see published decks.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are listed first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='The question or term. Markdown is supported.')),
                ('back', models.TextField(help_text='The answer or explanation. Markdown is supported.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='quizzes.deck')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known', models.BooleanField(default=False)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_reviews', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quizzes.flashcard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'card'), name='uniq_user_card')],
            },
        ),
    ]
